apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonsampleapplication
  labels:
    app: pythonsampleapplication
    kubernetes.azure.com/generator: devhub
  namespace: python-sample-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonsampleapplication
  template:
    metadata:
      labels:
        app: pythonsampleapplication
    spec:
      containers:
        - name: pythonsampleapplication
          image: acrregistrydeb001.azurecr.io/pythonsampleimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
