apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    owner: user
  name: nginxprodv1
  namespace: prod
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}